[theme]
primaryColor = "#38bdf8"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

[client]
showErrorDetails = false

[server]
enableCORS = false
enableXsrfProtection = true